// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVC6LxdIiopg-PiO9qxZ2ELKFqBPKyI5w',
    appId: '1:254414964964:web:79559cc299fb08f897c4f1',
    messagingSenderId: '254414964964',
    projectId: 'mad-prog1',
    authDomain: 'mad-prog1.firebaseapp.com',
    storageBucket: 'mad-prog1.firebasestorage.app',
    measurementId: 'G-Q33F49RG6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLttIoud0sRn49fgTh_zXB-6k7q7EfRfI',
    appId: '1:254414964964:android:0eef1a67d168e59d97c4f1',
    messagingSenderId: '254414964964',
    projectId: 'mad-prog1',
    storageBucket: 'mad-prog1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Uf2txl92oT8SHaWqTST7yf6ezR2H1cw',
    appId: '1:254414964964:ios:998bcd68b67a96a997c4f1',
    messagingSenderId: '254414964964',
    projectId: 'mad-prog1',
    storageBucket: 'mad-prog1.firebasestorage.app',
    iosBundleId: 'com.example.finApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Uf2txl92oT8SHaWqTST7yf6ezR2H1cw',
    appId: '1:254414964964:ios:998bcd68b67a96a997c4f1',
    messagingSenderId: '254414964964',
    projectId: 'mad-prog1',
    storageBucket: 'mad-prog1.firebasestorage.app',
    iosBundleId: 'com.example.finApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVC6LxdIiopg-PiO9qxZ2ELKFqBPKyI5w',
    appId: '1:254414964964:web:a766f8c7dac9c0ce97c4f1',
    messagingSenderId: '254414964964',
    projectId: 'mad-prog1',
    authDomain: 'mad-prog1.firebaseapp.com',
    storageBucket: 'mad-prog1.firebasestorage.app',
    measurementId: 'G-FVR0PERCHY',
  );
}
